# Generated by Django 3.2.5 on 2021-07-08 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_review_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='thumbnailUrl',
        ),
    ]
